// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMJp15UHlLzMsMvNNw0NnZrMYEccL1J9o',
    appId: '1:222853214162:android:414f74a0676c4242a4620b',
    messagingSenderId: '222853214162',
    projectId: 'fir-test-edb81',
    databaseURL: 'https://fir-test-edb81-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-edb81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYhsuyLRvzOtRmJmLnkR64xAZiofUK5s0',
    appId: '1:222853214162:ios:32381df87fb37a5aa4620b',
    messagingSenderId: '222853214162',
    projectId: 'fir-test-edb81',
    databaseURL: 'https://fir-test-edb81-default-rtdb.firebaseio.com',
    storageBucket: 'fir-test-edb81.appspot.com',
    iosClientId: '222853214162-5t96r4ggum11jbr1rigmmaknhv9q73tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.lassarusBluetoothInterface',
  );
}
